In [1]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
data = [[-1,2],[-0.5,6],[0,10],[1,18]]
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

### 数据归一化

In [2]:
#实现归一化
scaler = MinMaxScaler()
scaler = scaler.fit(data)
result = scaler.transform(data) #到处归一化后的结果
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [3]:
result1 = scaler.fit_transform(data)
result1

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [4]:
scaler.inverse_transform(result) #返回没有归一化的原始数据

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [5]:
scaler = MinMaxScaler(feature_range=(5,10))
scaler.fit_transform(data)


array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [8]:
import numpy as np
X  = np.array(data)
X


array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [11]:
X.min(axis=0)

array([5., 5.])

### 数据标准化

In [13]:
from sklearn.preprocessing import StandardScaler
standsc =  StandardScaler()
standsc = standsc.fit(data) #fit 的本质是求均值和方差

StandardScaler(copy=True, with_mean=True, with_std=True)

In [15]:
standsc.mean_
standsc.var_  #方差

array([3.41796875, 3.41796875])

In [19]:
std = standsc.fit_transform(data)
std

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [21]:
standsc.inverse_transform(std)

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

### 缺失值

In [30]:
import pandas as pd
test_data = pd.read_csv(r'C:\Users\lou\Desktop\枫枫的小仙女\菜菜sklearn课件\03数据预处理和特征工程\Narrativedata.csv',index_col=0)
#index_col 指定第一列为index

test_data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [31]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         714 non-null float64
Sex         891 non-null object
Embarked    889 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [47]:
Age = test_data.loc[:,'Age'].values.reshape(-1,1)

In [44]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer() #默认均值填补
imp_median = SimpleImputer(strategy='median')
imp_0 = SimpleImputer(strategy='constant',fill_value=0)

In [48]:
imp_mean = imp_mean.fit_transform(Age)
imp_median = imp_median.fit_transform(Age)
imp_0 = imp_0.fit_transform(Age)

In [50]:
imp_mean[:10]

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ]])

In [52]:
imp_median[:10]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [28.],
       [54.],
       [ 2.],
       [27.],
       [14.]])

In [53]:
imp_0[:10]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [ 0.],
       [54.],
       [ 2.],
       [27.],
       [14.]])

In [55]:
imp_0.shape

(891, 1)

In [56]:
test_data.loc[:,'Age'] = imp_median

In [61]:
Embarked = test_data.loc[:,'Embarked'].values.reshape(-1,1)
imp_mode =  SimpleImputer(strategy='most_frequent')
test_data.loc[:,'Embarked'] = imp_mode.fit_transform(Embarked)

In [62]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
Age         891 non-null float64
Sex         891 non-null object
Embarked    891 non-null object
Survived    891 non-null object
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


### 处理分类型特征：编码与哑变量

In [70]:
from sklearn.preprocessing import LabelEncoder
# LabelEncoder: 标签专用，能够将分类转换为分类数值
y = test_data.iloc[:,-1]
le = LabelEncoder()
le = le.fit(y)
label = le.transform(y)
test_data.iloc[:,-1] = label

In [77]:
from sklearn.preprocessing import OrdinalEncoder 
#OrdinalEncoder 特征专用，能够将分类特征转换为分类数值
data_ = test_data.copy()
OrdinalEncoder().fit(data_.iloc[:,1:-1]).categories_
data_.iloc[:,1:-1] = OrdinalEncoder().fit_transform(data_.iloc[:,1:-1])
data_.head()

Age  Sex  Embarked  Survived
0  22.0  1.0       2.0         0
1  38.0  0.0       0.0         2
2  26.0  0.0       2.0         2
3  35.0  0.0       2.0         2
4  35.0  1.0       2.0         0

In [84]:
from sklearn.preprocessing import OneHotEncoder
X = test_data.iloc[:,1:-1]

enc = OneHotEncoder(categories='auto').fit(X)
result = enc.transform(X).toarray()
result  #哑变量

#OneHotEncoder(categories='auto').fit_transform(X).toarray() 一步到位


array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

###  特征选择

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r'C:\Users\lou\Desktop\枫枫的小仙女\菜菜sklearn课件\03数据预处理和特征工程\digit recognizor.csv')
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [3]:
x = data.iloc[:,1:]
y = data.iloc[:,0]

####  1.方差过滤法

In [4]:
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold() #默认方差为0
X_var0 = selector.fit_transform(x)
X_var0.shape

(42000, 708)

In [96]:
#将方差设置为中位数
med = np.median(x.var().values)
x_med = VarianceThreshold(threshold=med).fit_transform(x)
x_med.shape

(42000, 392)

In [97]:
#二分类特征中某中分类占到80%以上的特征 删除特征
x_bvar = VarianceThreshold(0.8*(1-0.8)).fit_transform(x)
x_bvar.shape

(42000, 685)

#### KNN 和随机森林在不同方差过滤效果下的对比

In [8]:
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.model_selection import cross_val_score
import numpy as np

#过滤前
x = data.iloc[:,1:]
y = data.iloc[:,0]

#过滤后
x_fsvar = VarianceThreshold(np.median(x.var().values)).fit_transform(x)


##### KNN 比较

In [ ]:
%%timeit
cross_val_score(KNN(),x,y,cv=5).mean() #未过滤之前使用KNN算法的准确率

In [ ]:
# 方差过滤后使用KNN后准确率
%%timeit
cross_val_score(KNN(),x_fsvar,y,cv=5).mean()

#####  随机森林比较

In [6]:
%%timeit
cross_val_score(RFC(n_estimators=10,random_state=0),x,y,cv=5).mean()

11.7 s ± 951 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit
cross_val_score(RFC(n_estimators=10,random_state=0),x_fsvar,y,cv=5).mean()

### 2.卡方过滤

In [7]:
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.model_selection import cross_val_score
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2


In [11]:
x_fschi = SelectKBest(chi2,k=300).fit_transform(x_fsvar,y)
x_fschi.shape

(42000, 300)

In [13]:
cross_val_score(RFC(n_estimators=10,random_state=0),x_fschi,y,cv=5).mean()

0.9333098667649198

In [14]:
chivalue,pvalue = chi2(x_fsvar,y) #返回卡方检验的卡方值和p值

In [15]:
chivalue

array([ 945664.84392643, 1244766.05139164, 1554872.30384525,
       1834161.78305343, 1903618.94085294, 1845226.62427198,
       1602117.23307537,  708535.17489837,  974050.20513718,
       1188092.19961931, 1319151.43467036, 1397847.8836796 ,
       1433554.26798015, 1429043.15373433, 1332663.17213405,
       1101423.25372261,  809989.56940485,  519266.71772284,
        285681.88297156,  191589.23696468,  902883.1255264 ,
       1237265.16042373, 1503477.73699155, 1625807.41495542,
       1630206.90922916, 1630597.02883804, 1633456.72909664,
       1610816.75571229, 1483382.49543886, 1256290.1574794 ,
        951236.1617682 ,  693192.66191748,  532386.96220361,
        504617.38933715,  575090.36046243,  501025.03733245,
        802341.10683194, 1078344.8724406 , 1226540.98318702,
       1269945.07968831, 1221758.57688808, 1146535.17810241,
       1080657.20185303, 1079065.30979135, 1092222.70610032,
       1064908.45385716, 1023327.00231067,  974163.15420165,
        918857.12860617,

In [16]:
pvalue

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [20]:
k = chivalue.shape[0] - (pvalue>0.05).sum() #所有保留的特征的数量
k

# x_fschi = SelectKBest(chi2,k=k).fit_transform(x_fsvar,y)
# cross_val_score(RFC(n_estimators=10,random_state=0),x_fschi,y,cv=5).mean()

392

### 3.F检验过滤